using Content.Shared._CMU14.Medical.Core;
using Content.Shared._CMU14.ZLevels;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CmuTab : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private const float OldZLevelBlurStrength = 2.0f;

    public event Action<bool, string>? CrtUiPreviewChanged;

    public CmuTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var crtUiEnabled = Control.AddOption(new OptionCrtUiEnabled(Control, _cfg, CrtUiEnabledCheckBox));
        crtUiEnabled.PreviewValueChanged += UpdateCrtUiOptionsPreview;

        // CRT colour picker (1/4) - switched off. Re-enable together with the slider in CmuTab.xaml
        // and the three blocks below. OptionCrtUiColor itself is left whole and untouched.
        // No SelectorType to set any more - CmuColorPicker is HSV by construction.
        // var crtUiColor = Control.AddOption(new OptionCrtUiColor(Control, _cfg, CrtUiColorSlider));
        // crtUiColor.PreviewValueChanged += UpdateCrtUiOptionsPreview;

        // Not previewed like the two above, and not hidden when CRT is off either - it only does
        // anything under the CRT theme, but it is an accessibility setting and hiding it behind
        // another toggle is how people fail to find it. It applies on Apply like every other
        // checkbox here.
        Control.AddOptionCheckBox(CCVars.CMUChatReadableFont, ChatReadableFontCheckBox);

        // Directly under the readable-font box because the two compose - they are the same setting
        // to a player ("make chat easier to read"), split only because one changes the face and the
        // other the size, and either is useful without the other.
        // Off first here, unlike the tint below: normal size is the default and the list reads as
        // strength ascending from it.
        Control.AddOptionDropDown(
            CCVars.CMUChatBigFont,
            ChatBigFontDropDown,
            [
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontOff,
                    Loc.GetString("ui-options-crt-chat-big-font-off")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontOne,
                    Loc.GetString("ui-options-crt-chat-big-font-one")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatBigFontTwo,
                    Loc.GetString("ui-options-crt-chat-big-font-two")),
            ]);

        // Muted first, because it is the default and the list reads as strength descending.
        Control.AddOptionDropDown(
            CCVars.CMUChatRowTint,
            ChatRowTintDropDown,
            [
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintMuted,
                    Loc.GetString("ui-options-crt-chat-row-tint-muted")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintFull,
                    Loc.GetString("ui-options-crt-chat-row-tint-full")),
                new OptionDropDownCVar<string>.ValueOption(
                    CCVars.CMUChatRowTintOff,
                    Loc.GetString("ui-options-crt-chat-row-tint-off")),
            ]);

        Control.AddOptionCheckBox(CCVars.ChatEnableRunechatBubbles, RunechatSpeechBubblesCheckBox);
        Control.AddOptionPercentSlider(CCVars.ChatRunechatBubbleScale, RunechatSpeechBubbleScaleSlider, 0.5f, 2f);
        Control.AddOptionCheckBox(CCVars.CMUVoteUiLarge, VoteUiLargeCheckBox);
        Control.AddOptionCheckBox(CCVars.ExamineLogInChat, ExamineLogInChatCheckBox);
        Control.AddOptionCheckBox(CCVars.ExamineFullTextInChat, ExamineFullTextInChatCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.TargetedHealingEnabled, TargetedHealingCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.AutoReapplyKitsEnabled, AutoReapplyKitsCheckBox);
        Control.AddOptionCheckBox(CMUMedicalCCVars.UiLessSurgeryEnabled, UiLessSurgeryCheckBox);
        Control.AddOptionCheckBox(CCVars.CMUScreamOnHotbarEnabled, ScreamOnHotbarCheckBox);
        Control.AddOptionPercentSlider(CMUZLevelsCVars.BlurStrength, ZLevelBlurSlider, scale: OldZLevelBlurStrength);

        Control.Initialize();
        UpdateCrtUiOptionsVisibility();
    }

    /// <summary>
    ///     Nothing to show or hide while the colour picker is switched off. Kept as a method so
    ///     re-enabling it is one uncommented line rather than a reshuffle of its two callers.
    /// </summary>
    private void UpdateCrtUiOptionsVisibility()
    {
        // CRT colour picker (2/4).
        // CrtUiColorSlider.Visible = CrtUiEnabledCheckBox.Pressed;
    }

    private void UpdateCrtUiOptionsPreview()
    {
        UpdateCrtUiOptionsVisibility();

        // CRT colour picker (3/4). With no picker to read, the preview uses the colour already in
        // the cvar - so toggling the theme on and off still previews in the configured colour
        // rather than snapping to a default the player never chose.
        CrtUiPreviewChanged?.Invoke(CrtUiEnabledCheckBox.Pressed, _cfg.GetCVar(CCVars.CrtUiColor));
        // CrtUiPreviewChanged?.Invoke(CrtUiEnabledCheckBox.Pressed, CrtUiColorSlider.Picker.Color.ToHex());
    }

    private sealed class OptionCrtUiEnabled : BaseOptionCVar<bool>
    {
        private readonly CheckBox _checkBox;
        private bool _suppressToggle;

        public event Action? PreviewValueChanged;

        protected override bool Value
        {
            get => _checkBox.Pressed;
            set
            {
                _suppressToggle = true;
                try
                {
                    _checkBox.Pressed = value;
                }
                finally
                {
                    _suppressToggle = false;
                }
            }
        }

        public OptionCrtUiEnabled(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            CheckBox checkBox)
            : base(controller, cfg, CCVars.CrtUiEnabled)
        {
            _checkBox = checkBox;
            _checkBox.OnToggled += _ =>
            {
                if (_suppressToggle)
                    return;

                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            base.LoadValue();
            NotifyPreviewValueChanged();
        }

        public override void SaveValue()
        {
            base.SaveValue();
            NotifyPreviewValueChanged();
        }

        public override void ResetToDefault()
        {
            base.ResetToDefault();
            NotifyPreviewValueChanged();
        }

        protected override void ValueChanged()
        {
            base.ValueChanged();
            NotifyPreviewValueChanged();
        }

        private void NotifyPreviewValueChanged()
        {
            PreviewValueChanged?.Invoke();
        }
    }

    /// <summary>
    ///     CRT colour picker (4/4). Unused while the picker is switched off - deliberately left
    ///     whole rather than deleted, so turning it back on is uncommenting, not rewriting.
    /// </summary>
    private sealed class OptionCrtUiColor : BaseOptionCVar<string>
    {
        private readonly OptionColorSlider _slider;
        private bool _suppressColorChanged;

        public event Action? PreviewValueChanged;

        protected override string Value
        {
            get => _slider.Picker.Color.ToHex();
            set
            {
                _suppressColorChanged = true;
                try
                {
                    _slider.Picker.Color = ResolveCrtColor(value);
                }
                finally
                {
                    _suppressColorChanged = false;
                }
            }
        }

        public OptionCrtUiColor(
            OptionsTabControlRow controller,
            IConfigurationManager cfg,
            OptionColorSlider slider)
            : base(controller, cfg, CCVars.CrtUiColor)
        {
            _slider = slider;

            slider.Picker.OnColorChanged += _ =>
            {
                if (_suppressColorChanged)
                    return;

                ValueChanged();
            };
        }

        public override void LoadValue()
        {
            base.LoadValue();
            NotifyPreviewValueChanged();
        }

        public override void SaveValue()
        {
            base.SaveValue();
            NotifyPreviewValueChanged();
        }

        public override void ResetToDefault()
        {
            base.ResetToDefault();
            NotifyPreviewValueChanged();
        }

        protected override void ValueChanged()
        {
            base.ValueChanged();
            NotifyPreviewValueChanged();
        }

        protected override bool IsValueEqual(string a, string b)
        {
            return ResolveCrtColor(a).ToHex() == ResolveCrtColor(b).ToHex();
        }

        private void NotifyPreviewValueChanged()
        {
            PreviewValueChanged?.Invoke();
        }

        private static Color ResolveCrtColor(string value)
        {
            if (Color.TryFromHex(value, out var color))
                return color;

            return value switch
            {
                CCVars.CrtUiColorBlue => Color.FromHex("#58CCFF"),
                CCVars.CrtUiColorOrange => Color.FromHex("#FFB454"),
                CCVars.CrtUiColorRed => Color.FromHex("#FF4E5E"),
                CCVars.CrtUiColorPurple => Color.FromHex("#C45BFF"),
                _ => Color.FromHex(CCVars.CrtUiColorDefault),
            };
        }
    }
}
