using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._AU14.Chemistry.Research;

[GenerateTypedNameReferences]
public sealed partial class AdminChemicalContractConsoleWindow : DefaultWindow
{
    public AdminChemicalContractConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
