using System.Linq;
using Content.Client.Camera;
using Content.Client.Resources;
using Content.Client.Viewport;
using Content.Shared.Camera;
using Content.Shared.SurveillanceCamera;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : DefaultWindow
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    public event Action<NetEntity>? CameraSelected;
    public event Action<NetEntity>? NetworkOpened;
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;

    private string _currentCameraName = string.Empty;
    private bool _isSwitching;
    private readonly FixedEye _defaultEye = new();
    private readonly Dictionary<NetEntity, int> _networkMap = new();
    private readonly Dictionary<NetEntity, int> _gridMap = new();
    private NetEntity? _selectedGrid;

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // This could be done better. I don't want to deal with stylesheets at the moment.
        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

        CameraView.ViewportSize = new Vector2i(500, 500);
        CameraView.RenderZLevels = true;
        CameraView.Eye = _defaultEye; // sure
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        MapCameraView.ViewportSize = new Vector2i(500, 500);
        MapCameraView.RenderZLevels = true;
        MapCameraView.Eye = _defaultEye;
        MapCameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        MapCameraViewBackground.Texture = texture;
        MapCameraViewBackground.ShaderOverride = shader;

        TabContainer.SetTabTitle(ListTab, Loc.GetString("surveillance-camera-monitor-ui-tab-list"));
        TabContainer.SetTabTitle(MapTab, Loc.GetString("surveillance-camera-monitor-ui-tab-map"));

        SubnetList.OnItemSelected += OnCameraListSelect;
        NetworkSelector.OnItemSelected += args =>
            NetworkOpened?.Invoke((NetEntity) args.Button.GetItemMetadata(args.Id)!);
        GridSelector.OnItemSelected += args =>
            CameraMap.SelectGrid((NetEntity) args.Button.GetItemMetadata(args.Id)!);
        CameraMap.CameraSelected += camera => CameraSelected?.Invoke(camera);
        CameraMap.GridChanged += OnCameraMapGridChanged;
        SubnetRefreshButton.OnPressed += _ => SubnetRefresh?.Invoke();
        CameraRefreshButton.OnPressed += _ => CameraRefresh?.Invoke();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect?.Invoke();
    }

    // The UI class gets the eye from the active entity, and passes it here to change the view.
    public void UpdateState(
        IEye? eye,
        CameraSessionDirectoryUiData directory,
        CameraMapUiState geometry)
    {
        MapTab.Visible = directory.MapEnabled;
        if (!directory.MapEnabled && MonitorTabs.CurrentTab == MapTab.GetPositionInParent())
            MonitorTabs.CurrentTab = ListTab.GetPositionInParent();

        _currentCameraName = directory.ActiveCameraName ?? string.Empty;
        SetCameraView(eye);
        PopulateNetworkSelector(directory.Networks, directory.ActiveNetwork);
        PopulateCameraList(directory.Cameras);
        if (directory.MapEnabled)
            PopulateMap(geometry, directory.ActiveCamera);
    }

    private void PopulateNetworkSelector(
        List<CameraSessionNetworkUiData> networks,
        NetEntity? activeNetwork)
    {
        NetworkSelector.Clear();
        _networkMap.Clear();

        if (networks.Count == 0)
        {
            NetworkSelector.AddItem(Loc.GetString("surveillance-camera-monitor-ui-no-networks"));
            NetworkSelector.Disabled = true;
            return;
        }

        NetworkSelector.Disabled = false;
        foreach (var network in networks)
        {
            NetworkSelector.AddItem(network.Name);
            var id = NetworkSelector.ItemCount - 1;
            NetworkSelector.SetItemMetadata(id, network.Network);
            _networkMap[network.Network] = id;
        }

        if (activeNetwork is { } selectedNetwork && _networkMap.TryGetValue(selectedNetwork, out var networkId))
            NetworkSelector.Select(networkId);
    }

    private void PopulateCameraList(List<CameraSessionCameraUiData> cameras)
    {
        var entries = cameras.Select(camera => new ItemList.Item(SubnetList)
        {
            Text = camera.Name,
            Metadata = camera.Camera,
        }).ToList();
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        SubnetList.SetItems(entries, (a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
    }

    private void PopulateMap(CameraMapUiState state, NetEntity? activeCamera)
    {
        GridSelector.Clear();
        _gridMap.Clear();

        foreach (var grid in state.Grids)
        {
            GridSelector.AddItem(grid.Name);
            var id = GridSelector.ItemCount - 1;
            GridSelector.SetItemMetadata(id, grid.Grid);
            _gridMap[grid.Grid] = id;
        }

        var selectedGrid = CameraMapSelection.SelectGrid(state, _selectedGrid, activeCamera);
        GridSelector.Disabled = selectedGrid == null;
        MapEmptyLabel.Visible = selectedGrid == null;
        CameraMap.Visible = selectedGrid != null;
        CameraMap.SetState(state, activeCamera);

        if (selectedGrid is { } selectedGridEntity && _gridMap.TryGetValue(selectedGridEntity, out var gridId))
            GridSelector.Select(gridId);
    }

    private void OnCameraMapGridChanged(NetEntity? grid)
    {
        _selectedGrid = grid;
        if (grid is { } selected && _gridMap.TryGetValue(selected, out var gridId))
            GridSelector.Select(gridId);
    }

    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        var viewEye = eye ?? _defaultEye;
        CameraView.Eye = viewEye;
        MapCameraView.Eye = viewEye;
        CameraView.Visible = !eyeChanged && !_isSwitching;
        MapCameraView.Visible = CameraView.Visible;
        CameraDisconnectButton.Disabled = eye == null;

        if (eye != null)
        {
            if (!eyeChanged)
                return;

            _isSwitching = true;
            CameraViewBackground.Visible = true;
            MapCameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                ("camera", _currentCameraName));
            MapCameraStatus.Text = CameraStatus.Text;
            CameraSwitchTimer?.Invoke();
        }
        else
        {
            CameraViewBackground.Visible = true;
            MapCameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status-disconnected");
            MapCameraStatus.Text = CameraStatus.Text;
        }
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        MapCameraView.Visible = CameraView.Visible;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        MapCameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
            ("camera", _currentCameraName));
        MapCameraStatus.Text = CameraStatus.Text;
    }

    private void OnCameraListSelect(ItemList.ItemListSelectedEventArgs args)
    {
        CameraSelected?.Invoke((NetEntity) SubnetList[args.ItemIndex].Metadata!);
    }
}
