using Content.Shared.AU14.Hospital;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Hospital;

[GenerateTypedNameReferences]
public sealed partial class HospitalEmergencyComputerWindow : DefaultWindow
{
    public HospitalEmergencyComputerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(HospitalEmergencyComputerBuiState state)
    {
        StatusLabel.Text = state.StatusText;
        LandingZoneLabel.Text = state.HasLandingZone
            ? "Landing zone: linked"
            : "Landing zone: unavailable";

        IncidentReportLabel.Text = string.IsNullOrWhiteSpace(state.IncidentReport)
            ? "No active incident."
            : state.IncidentReport;

        CasualtiesLabel.Text = state.Casualties.ToString();
        SeverityLabel.Text = state.Severity == 0 ? "--" : $"{state.Severity} / 3";
        RewardLabel.Text = $"${state.Reward}";
        PatientsLabel.Text = $"{state.ActivePatients} active / {state.FullyHealedPatients} cleared";
        TimerLabel.Text = state.SecondsRemaining > 0 ? $"{state.SecondsRemaining}s" : "--";

        var vipAudit = state.LastVipPenalty > 0
            ? $", ${state.LastVipPenalty} VIP penalty"
            : string.Empty;
        var deathAudit = state.LastPermanentDeathPenalty > 0
            ? $", ${state.LastPermanentDeathPenalty} death penalty"
            : string.Empty;

        AuditLabel.Text = state.LastPayout > 0 ||
            state.LastMissedInjuries > 0 ||
            state.LastVipPenalty > 0 ||
            state.LastPermanentDeathPenalty > 0
            ? $"Last audit: ${state.LastPayout} paid, {state.LastMissedInjuries} missed injuries{vipAudit}{deathAudit}"
            : "Last audit: no payout recorded";

        ApproveLandingButton.Disabled = !state.CanApproveLanding;
        SkipContractButton.Disabled = !state.CanSkipContract;
        RequestPickupButton.Disabled = !state.CanRequestPickup;
        ReleaseShuttleButton.Disabled = !state.CanReleaseShuttle;
    }
}
