using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Robust.Client.ResourceManagement;
using Prometheus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyCharacterPreviewPanel : Control
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IResourceCache _resourceCache = default!;

    public Button CharacterSetupButton => CharacterSetup;
    public Button LinkAccountButtonControl => LinkAccountButton;
    public Button PrevCharacterButton => PrevCharButton;
    public Button NextCharacterButton => NextCharButton;
    public Button IgnoreAllegianceToggle => IgnoreAllegianceButton;

    /// <summary>
    ///     Must match the size the CrtCharacterSummary style rule uses, or the one-line clamp on the
    ///     name is measured against the wrong font.
    /// </summary>
    private const int CharacterSummaryFontSize = 9;


    private EntityUid? _previewDummy;

    public LobbyCharacterPreviewPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // The CRT theme styles every button label at one size via a stylesheet rule. FontOverride
        // is the reliable way to make just this one bigger - another style class would tie with
        // that rule on specificity.
        if (StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.Label.FontOverride = StyleNano.GetCrtFont(_resourceCache, 10);

        // Base menu only: toggled on turns the button solid red. The default Pressed state for a
        // plain Button is a thin highlighted border, easy to miss at a glance for something that
        // changes spawn behaviour. The CRT theme already themes every button consistently through
        // CrtButton, so this is left alone there.
        if (!StyleNano.CrtUiEnabled)
            IgnoreAllegianceButton.AddStyleClass(StyleNano.StyleClassButtonToggleRed);

        // Colour alone is never a safe state indicator - readable differently depending on vision,
        // and on the CRT theme specifically the accent is player-configurable, so "red" can't be
        // assumed to contrast with it. The label states on/off directly instead.
        UpdateIgnoreAllegianceText(IgnoreAllegianceButton.Pressed);
        IgnoreAllegianceButton.OnToggled += args => UpdateIgnoreAllegianceText(args.Pressed);
    }

    private void UpdateIgnoreAllegianceText(bool pressed)
    {
        IgnoreAllegianceButton.Text = Loc.GetString(pressed
            ? "lobby-character-preview-ignore-allegiance-on"
            : "lobby-character-preview-ignore-allegiance-off");
    }

    public void SetLoaded(bool value)
    {
        Loaded.Visible = value;
        Unloaded.Visible = !value;
    }

    /// <summary>
    ///     Sets the two-line character summary. Both lines are markup so the name, pronoun and age
    ///     can be coloured; see the lobby-character-summary-* locale keys.
    /// </summary>
    public void SetSummaryText(string nameMarkup, string ageMarkup)
    {
        ClampNameToOneLine();
        SetSummaryLine(SummaryName, nameMarkup);
        SetSummaryLine(SummaryAge, ageMarkup);
    }

    /// <summary>
    ///     The summary column is a fixed share of the panel, so an over-long name wraps instead of
    ///     shoving the sprite sideways. Cap it at a single line and let the rest clip: names are
    ///     bounded in length anyway, and a second line would push the age, job line and toggle down.
    /// </summary>
    private void ClampNameToOneLine()
    {
        // Only meaningful for the CRT font, which is the one the CrtCharacterSummary rule applies.
        // Without CRT the label keeps NanoUI's font and is left to wrap as before.
        if (!StyleNano.CrtUiEnabled)
            return;

        // Read the scale off the control rather than repeating the stylesheet's value - this runs
        // when a profile loads, long after styles have resolved.
        var lineHeight = StyleNano.GetCrtFont(_resourceCache, CharacterSummaryFontSize)
            .GetLineHeight(1f);

        // Height is capped to one line so a long name cannot push the rest of the block down. The
        // width cap that used to sit beside this is gone: it made the name *wrap*, and this cap then
        // hid the wrapped line - so "Zachary Thompson" rendered as "Zachary". The stats column that
        // cap was protecting no longer exists, so there is nothing left to protect.
        SummaryName.MaxHeight = lineHeight * SummaryName.LineHeightScale;

    }

    private static void SetSummaryLine(RichTextLabel label, string markup)
    {
        if (string.IsNullOrWhiteSpace(markup))
        {
            label.SetMessage(FormattedMessage.Empty);
            label.Visible = false;
            return;
        }

        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markup));
        label.Visible = true;
    }

    public void SetJobText(string value)
    {
        JobSummary.Text = value;
        JobSummary.Visible = !string.IsNullOrWhiteSpace(value);
    }

    public void SetSprite(EntityUid uid)
    {
        if (_previewDummy != null)
        {
            _entManager.DeleteEntity(_previewDummy);
        }

        _previewDummy = uid;

        ViewBox.DisposeAllChildren();
        var spriteView = new SpriteView
        {
            OverrideDirection = Direction.South,
            // Down from 4x/112. The sprite was the tallest thing in the block and set its height,
            // which is the height the stats column beside it has to match; smaller here buys the row
            // back the vertical space without costing legibility on a 32px source sprite.
            Scale = new Vector2(3f, 3f),
            MaxSize = new Vector2(84, 84),
            Stretch = SpriteView.StretchMode.Fill,
        };
        spriteView.SetEntity(uid);
        ViewBox.AddChild(spriteView);
    }

    [System.Obsolete]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _entManager.DeleteEntity(_previewDummy);
        _previewDummy = null;
    }
}
