using Content.Client._CMU14.Interface;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.CCVar;
using Robust.Client.Graphics;
using Robust.Shared.Configuration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        private const float BalanceRatingBottomMargin = 84f;

        /// <summary>
        ///     The round timer now lives inside the server-info block so it sits between the round
        ///     table and the player count. Exposed here so LobbyState can keep driving it.
        /// </summary>
        public Label StationTime => ServerInfo.RoundTimeLabel;

        [Dependency] private IClientConsoleHost _consoleHost = default!;
        [Dependency] private IConfigurationManager _cfg = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            PositionBalanceRatingContainer();
            CrtLobbyTheme.Apply(MainContainer);

            // Keep the chat's usual dark backing, but drop its border so it reads as a band running
            // the full width of the lobby panel rather than a second rectangle inside it. The chat
            // deliberately keeps its own colour instead of the CRT palette - it has to stay legible.
            // Only the lobby does this; the in-round chat floats over the game and still needs its
            // outline. The negative margins in the XAML are what let this backing reach the edges.
            // Swap the style class rather than setting PanelOverride: a colour baked into a control
            // goes stale when the CRT palette changes, whereas the stylesheet is rebuilt.
            Chat.ChatWindowPanel.RemoveStyleClass(StyleNano.StyleClassChatPanel);
            Chat.ChatWindowPanel.AddStyleClass(StyleNano.StyleClassCrtChatPanel);

            // Same treatment for the input row, so its border tracks the palette too.
            Chat.ChatInput.RemoveStyleClass(StyleNano.StyleClassChatSubPanel);
            Chat.ChatInput.AddStyleClass(StyleNano.StyleClassCrtChatInput);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            SetUpLobbyCrt();
            _cfg.OnValueChanged(CCVars.CMUCrtMenuEffect, OnMenuEffectChanged);
            _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtEnabledChanged);
        }

        private void OnMenuEffectChanged(bool _) => SetUpLobbyCrt();
        private void OnCrtEnabledChanged(bool _) => SetUpLobbyCrt();

        /// <summary>
        ///     The prop-terminal treatment on the lobby column above the chat. Decides what the tube
        ///     is showing and how hard it is worked; the effect's own amplitudes come from the shared
        ///     cvars inside <see cref="CrtScreenControl"/>.
        /// </summary>
        private void SetUpLobbyCrt()
        {
            // The cvar, not StyleNano's cached copy. That static starts life at its compile-time
            // default of true and is only corrected once StylesheetManager initialises, so anything
            // reading it earlier gets "CRT is on" and bakes a green into a PanelOverride that no
            // later rebuild touches - the override is a snapshot, and only this method clears it.
            // That is exactly what left the whole server-info column painted Surface0 green with the
            // theme switched off. The cvar is right from the moment it is parsed.
            var crt = _cfg.GetCVar(CCVars.CrtUiEnabled);

            // Two planes, one step apart: Surface0 behind the whole column and Surface1 for the
            // server-info block, so that block reads as a section inside a screen rather than the
            // whole field being flat. That is the mock's Surface0/Surface1 relationship, and it only
            // works because those constants are genuinely different luminances - the shipped CRT
            // palette packs every surface into about five percent of the range and cannot do it.
            //
            // Both are only visible because their contents are inset in the XAML; with rows flush to
            // the edges there is no air for a backdrop to show through. They also stop the shader
            // writing black: it writes opaque, so any transparent region in the captured subtree
            // would come back black without something solid underneath.
            //
            // A literal colour is safe in a PanelOverride. The snapshot bug this method used to carry
            // came from reading the *theme-dependent* StyleNano.CrtPanelBackground getter once, before
            // StylesheetManager had corrected _crtUiEnabled from its compile-time default of true.
            // These are constants, and the override is re-applied whenever either cvar changes.
            // Surface0, the same plane as the column behind it. This was Surface1 - a lighter block
            // under the whole server-info section - but the mock has no such intermediate plane: the
            // cells carry the tones and the space between them is the tube. A lighter block under
            // them flattened the difference between the cell fills and put a visible rectangle edge
            // around the section, which is the box this panel keeps growing back.
            // Surface1, one rung up from the chat below it. The two zones tile the whole sidebar, so
            // this is not a lighter block sitting on a field - it is the ground changing at the seam,
            // and that change is what divides the sidebar without anything being stroked.
            //
            // ServerInfoBacking and CharacterBacking follow it exactly. They exist to stop the shader
            // writing black through transparent gaps, not to be seen; left on Surface0 under a
            // Surface1 zone each would read as a darker rectangle, which is the box this panel keeps
            // growing back.
            ServerInfoBacking.PanelOverride = crt
                ? new StyleBoxFlat { BackgroundColor = CrtTerminalPalette.Surface1 }
                : null;

            CharacterPreview.CharacterBacking.PanelOverride = crt
                ? new StyleBoxFlat { BackgroundColor = CrtTerminalPalette.Surface1 }
                : null;

            LobbyCrtBacking.PanelOverride = crt
                ? new StyleBoxFlat { BackgroundColor = CrtTerminalPalette.Surface1 }
                : null;

            // Left in place for base mode, where clearing the override above hands the panel back to
            // the stylesheet rule.
            if (!ServerInfoBacking.HasStyleClass(StyleNano.StyleClassCrtPanelFill))
                ServerInfoBacking.AddStyleClass(StyleNano.StyleClassCrtPanelFill);

            if (!CharacterPreview.CharacterBacking.HasStyleClass(StyleNano.StyleClassCrtPanelFill))
                CharacterPreview.CharacterBacking.AddStyleClass(StyleNano.StyleClassCrtPanelFill);

            LobbyCrt.Source = LobbyCrtContent;
            LobbyCrt.Phosphor = StyleNano.CrtGreen;

            // Everything the mock does except the bulge. Curvature is the one part of that look that
            // cannot survive here: the mock earns its barrel from a bezel PNG whose bowed cut-out
            // masks the corners, and there is no bezel around a panel embedded in the lobby, so the
            // warp would just bend straight text against a square edge. Vignette and the roll bar stay
            // at cvar strength - they are most of what reads as a tube.
            LobbyCrt.Curvature = 0f;
            LobbyCrt.Visible = _cfg.GetCVar(CCVars.CMUCrtMenuEffect) && crt;

            // The chat's raster. Gated on the same cvar as the block above so the sidebar is either
            // a screen or it is not; the overlay checks the theme flag itself every frame.
            ChatScanlines.Visible = _cfg.GetCVar(CCVars.CMUCrtMenuEffect) && crt;
        }

        public void PositionBalanceRatingContainer()
        {
            SetAnchorAndMarginPreset(BalanceRatingContainer, LayoutPreset.BottomLeft, margin: 10);
            SetMarginTop(
                BalanceRatingContainer,
                -BalanceRatingContainer.DesiredSize.Y - BalanceRatingBottomMargin);
            SetMarginBottom(BalanceRatingContainer, -BalanceRatingBottomMargin);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
