using System.Linq;
using Content.Client.Viewport;
using Content.Shared._RMC14.Camera;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Camera;

[GenerateTypedNameReferences]
public sealed partial class RMCCameraNetworkEditorControl : BoxContainer
{
    private RMCCameraNetworkEditorUiState _state = new(0, [], []);
    private readonly HashSet<NetEntity> _cameraMemberships = [];
    private readonly Dictionary<NetEntity, CheckBox> _membershipBoxes = [];
    private NetEntity? _selectedCamera;
    private NetEntity? _selectedNetwork;
    private uint? _errorRevision;
    private bool _pending;

    public event Action<RMCCameraNetworkEditorCreateBuiMsg>? CreateRequested;
    public event Action<RMCCameraNetworkEditorRenameBuiMsg>? RenameRequested;
    public event Action<RMCCameraNetworkEditorDeleteBuiMsg>? DeleteRequested;
    public event Action<RMCCameraNetworkEditorSetHiddenBuiMsg>? HiddenRequested;
    public event Action<RMCCameraNetworkEditorSaveCameraBuiMsg>? SaveCameraRequested;
    public event Action<NetEntity?>? EditorCameraSelected;

    public NetEntity? SelectedCamera => _selectedCamera;
    public NetEntity? SelectedNetwork => _selectedNetwork;
    public bool Pending => _pending;

    public RMCCameraNetworkEditorControl()
    {
        RobustXamlLoader.Load(this);
        CameraPreview.ViewportSize = new Vector2i(720, 520);
        CameraPreview.RenderZLevels = true;
        CameraPreview.Eye = new FixedEye();

        CameraSearchEdit.OnTextChanged += args => FilterCameras(args.Text);
        CreateNetworkButton.OnPressed += _ => Send(BuildCreateNetworkMessage(NetworkNameEdit.Text), CreateRequested);
        RenameNetworkButton.OnPressed += _ => Send(BuildRenameNetworkMessage(), RenameRequested);
        HideNetworkButton.OnPressed += _ =>
        {
            if (SelectedNetworkData() is { } selected)
                Send(BuildSetHiddenMessage(!selected.Hidden), HiddenRequested);
        };
        DeleteNetworkButton.OnPressed += _ => ConfirmDeleteNetworkButton.Visible = true;
        ConfirmDeleteNetworkButton.OnPressed += _ => Send(BuildDeleteNetworkMessage(), DeleteRequested);
        SaveCameraButton.OnPressed += _ => Send(BuildSaveCameraMessage(), SaveCameraRequested);
    }

    public void SetState(RMCCameraNetworkEditorUiState state)
    {
        _state = state;
        SetPending(false);
        if (_errorRevision != state.Revision)
        {
            _errorRevision = null;
            ErrorLabel.Visible = false;
        }
        ConfirmDeleteNetworkButton.Visible = false;

        RebuildNetworkRows();
        RebuildCameraRows();

        if (_selectedNetwork is { } selectedNetwork && state.Networks.Any(network => network.Id == selectedNetwork))
            SelectNetwork(selectedNetwork);
        else
            ClearNetworkSelection();

        if (_selectedCamera is { } selectedCamera && state.Cameras.Any(camera => camera.Camera == selectedCamera))
            SelectCamera(selectedCamera);
        else
            ClearCameraSelection();

        FilterCameras(CameraSearchEdit.Text);
    }

    public void SelectNetwork(NetEntity network)
    {
        var selected = _state.Networks.FirstOrDefault(candidate => candidate.Id == network);
        if (selected == null)
        {
            ClearNetworkSelection();
            return;
        }

        _selectedNetwork = network;
        NetworkNameEdit.Text = selected.Name;
        RenameNetworkButton.Disabled = _pending;
        HideNetworkButton.Visible = selected.Origin == RMCCameraNetworkEditorOrigin.Seeded;
        HideNetworkButton.Text = Loc.GetString(selected.Hidden
            ? "rmc-camera-editor-restore"
            : "rmc-camera-editor-hide");
        DeleteNetworkButton.Visible = selected.Origin == RMCCameraNetworkEditorOrigin.Owned;
        ConfirmDeleteNetworkButton.Visible = false;
    }

    public void SelectCamera(NetEntity camera)
    {
        var selected = _state.Cameras.FirstOrDefault(candidate => candidate.Camera == camera);
        if (selected == null)
        {
            ClearCameraSelection();
            return;
        }

        _selectedCamera = camera;
        CameraNameEdit.Text = selected.Name;
        _cameraMemberships.Clear();
        _cameraMemberships.UnionWith(selected.Networks);
        RebuildMembershipRows();
        SaveCameraButton.Disabled = _pending;
        EditorCameraSelected?.Invoke(camera);
    }

    public void SetCameraMembership(NetEntity network, bool selected)
    {
        if (selected)
            _cameraMemberships.Add(network);
        else
            _cameraMemberships.Remove(network);

        if (_membershipBoxes.TryGetValue(network, out var checkBox))
            checkBox.Pressed = selected;
    }

    public void FilterCameras(string search)
    {
        foreach (var child in CameraRows.Children)
        {
            if (child is not RMCCameraNetworkEditorCameraRow row)
                continue;

            row.Visible = string.IsNullOrWhiteSpace(search) ||
                row.CameraName.Contains(search, StringComparison.OrdinalIgnoreCase);
        }
    }

    public RMCCameraNetworkEditorCreateBuiMsg BuildCreateNetworkMessage(string name)
    {
        return new RMCCameraNetworkEditorCreateBuiMsg(_state.Revision, name);
    }

    public RMCCameraNetworkEditorRenameBuiMsg? BuildRenameNetworkMessage()
    {
        return _selectedNetwork is { } network
            ? new RMCCameraNetworkEditorRenameBuiMsg(_state.Revision, network, NetworkNameEdit.Text)
            : null;
    }

    public RMCCameraNetworkEditorDeleteBuiMsg? BuildDeleteNetworkMessage()
    {
        return _selectedNetwork is { } network
            ? new RMCCameraNetworkEditorDeleteBuiMsg(_state.Revision, network)
            : null;
    }

    public RMCCameraNetworkEditorSetHiddenBuiMsg? BuildSetHiddenMessage(bool hidden)
    {
        return _selectedNetwork is { } network
            ? new RMCCameraNetworkEditorSetHiddenBuiMsg(_state.Revision, network, hidden)
            : null;
    }

    public RMCCameraNetworkEditorSaveCameraBuiMsg? BuildSaveCameraMessage()
    {
        if (_selectedCamera is not { } camera)
            return null;

        var orderedMemberships = _state.Networks
            .Where(network => !network.Hidden && _cameraMemberships.Contains(network.Id))
            .Select(network => network.Id)
            .ToList();
        return new RMCCameraNetworkEditorSaveCameraBuiMsg(
            _state.Revision,
            camera,
            CameraNameEdit.Text,
            orderedMemberships);
    }

    public void SetPending(bool pending)
    {
        _pending = pending;
        CreateNetworkButton.Disabled = pending;
        NetworkNameEdit.Editable = !pending;
        RenameNetworkButton.Disabled = pending || _selectedNetwork == null;
        HideNetworkButton.Disabled = pending || _selectedNetwork == null;
        DeleteNetworkButton.Disabled = pending || _selectedNetwork == null;
        ConfirmDeleteNetworkButton.Disabled = pending || _selectedNetwork == null;
        CameraNameEdit.Editable = !pending && _selectedCamera != null;
        SaveCameraButton.Disabled = pending || _selectedCamera == null;
        foreach (var checkBox in _membershipBoxes.Values)
            checkBox.Disabled = pending;
    }

    public void ShowResult(RMCCameraNetworkEditorResultBuiMsg result)
    {
        SetPending(false);
        _errorRevision = result.Revision;
        ErrorLabel.Text = Loc.GetString(result.Error switch
        {
            RMCCameraNetworkEditorError.AccessDenied => "rmc-camera-editor-error-access-denied",
            RMCCameraNetworkEditorError.StaleRevision => "rmc-camera-editor-error-stale-revision",
            RMCCameraNetworkEditorError.InvalidName => "rmc-camera-editor-error-invalid-name",
            RMCCameraNetworkEditorError.DuplicateName => "rmc-camera-editor-error-duplicate-name",
            RMCCameraNetworkEditorError.MissingCamera => "rmc-camera-editor-error-missing-camera",
            RMCCameraNetworkEditorError.InvalidNetwork => "rmc-camera-editor-error-invalid-network",
            RMCCameraNetworkEditorError.SeededNetworkCannotBeDeleted => "rmc-camera-editor-error-seeded-delete",
            _ => "rmc-camera-editor-error-unknown",
        });
        ErrorLabel.Visible = result.Error != RMCCameraNetworkEditorError.None;
    }

    private void RebuildNetworkRows()
    {
        for (var index = 0; index < _state.Networks.Count; index++)
        {
            RMCCameraNetworkEditorNetworkRow row;
            if (index < NetworkRows.ChildCount && NetworkRows.GetChild(index) is RMCCameraNetworkEditorNetworkRow existing)
                row = existing;
            else
            {
                row = new RMCCameraNetworkEditorNetworkRow { HorizontalExpand = true };
                row.Selected += SelectNetwork;
                NetworkRows.AddChild(row);
            }

            var data = _state.Networks[index];
            var origin = Loc.GetString(data.Origin == RMCCameraNetworkEditorOrigin.Owned
                ? "rmc-camera-editor-origin-owned"
                : "rmc-camera-editor-origin-seeded");
            var hidden = data.Hidden ? $" - {Loc.GetString("rmc-camera-editor-hidden")}" : string.Empty;
            row.Bind(data.Id, $"{data.Name} ({origin}{hidden})");
        }

        TrimRows(NetworkRows, _state.Networks.Count);
    }

    private void RebuildCameraRows()
    {
        for (var index = 0; index < _state.Cameras.Count; index++)
        {
            RMCCameraNetworkEditorCameraRow row;
            if (index < CameraRows.ChildCount && CameraRows.GetChild(index) is RMCCameraNetworkEditorCameraRow existing)
                row = existing;
            else
            {
                row = new RMCCameraNetworkEditorCameraRow { HorizontalExpand = true };
                row.Selected += SelectCamera;
                CameraRows.AddChild(row);
            }

            row.Bind(_state.Cameras[index]);
        }

        TrimRows(CameraRows, _state.Cameras.Count);
    }

    private void RebuildMembershipRows()
    {
        MembershipRows.Children.Clear();
        _membershipBoxes.Clear();
        foreach (var network in _state.Networks.Where(network => !network.Hidden))
        {
            var checkBox = new CheckBox
            {
                Text = network.Name,
                Pressed = _cameraMemberships.Contains(network.Id),
                Disabled = _pending,
            };
            var networkId = network.Id;
            checkBox.OnToggled += args => SetCameraMembership(networkId, args.Pressed);
            MembershipRows.AddChild(checkBox);
            _membershipBoxes.Add(network.Id, checkBox);
        }
    }

    private void ClearNetworkSelection()
    {
        _selectedNetwork = null;
        NetworkNameEdit.Text = string.Empty;
        RenameNetworkButton.Disabled = true;
        HideNetworkButton.Visible = false;
        DeleteNetworkButton.Visible = false;
        ConfirmDeleteNetworkButton.Visible = false;
    }

    private void ClearCameraSelection()
    {
        _selectedCamera = null;
        CameraNameEdit.Text = string.Empty;
        _cameraMemberships.Clear();
        MembershipRows.Children.Clear();
        _membershipBoxes.Clear();
        SaveCameraButton.Disabled = true;
        CameraPreview.Eye = new FixedEye();
        EditorCameraSelected?.Invoke(null);
    }

    private RMCCameraNetworkEditorNetworkUiData? SelectedNetworkData()
    {
        return _selectedNetwork is { } selected
            ? _state.Networks.FirstOrDefault(network => network.Id == selected)
            : null;
    }

    private void Send<T>(T? message, Action<T>? handler) where T : BoundUserInterfaceMessage
    {
        if (message == null || handler == null || _pending)
            return;

        SetPending(true);
        handler(message);
    }

    private static void TrimRows(BoxContainer container, int count)
    {
        for (var index = container.ChildCount - 1; index >= count; index--)
            container.RemoveChild(index);
    }
}

public sealed class RMCCameraNetworkEditorCameraRow : Button
{
    public NetEntity Camera { get; private set; }
    public string CameraName { get; private set; } = string.Empty;
    public event Action<NetEntity>? Selected;

    public RMCCameraNetworkEditorCameraRow()
    {
        OnPressed += _ => Activate();
    }

    public void Bind(RMCCameraNetworkEditorCameraUiData camera)
    {
        Camera = camera.Camera;
        CameraName = camera.Name;
        Text = camera.Name;
    }

    public void Activate()
    {
        Selected?.Invoke(Camera);
    }
}

public sealed class RMCCameraNetworkEditorNetworkRow : Button
{
    public NetEntity Network { get; private set; }
    public event Action<NetEntity>? Selected;

    public RMCCameraNetworkEditorNetworkRow()
    {
        OnPressed += _ => Selected?.Invoke(Network);
    }

    public void Bind(NetEntity network, string text)
    {
        Network = network;
        Text = text;
    }
}
