using Content.Client.Camera;
using Content.Client._RMC14.UserInterface;
using Content.Shared.Camera;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._RMC14.Camera;

[GenerateTypedNameReferences]
public sealed partial class RMCCameraWindow : RMCPopOutWindow
{
    private readonly Dictionary<NetEntity, int> _gridMap = new();
    private NetEntity? _selectedGrid;

    public event Action<NetEntity>? CameraSelected;

    protected override Control Control => MonitorTabs;

    public RMCCameraWindow()
    {
        RobustXamlLoader.Load(this);
        Viewport.ViewportSize = new Vector2i(1200, 1200);
        Viewport.RenderZLevels = true;
        Viewport.Eye = new FixedEye();
        MapViewport.ViewportSize = new Vector2i(1200, 1200);
        MapViewport.RenderZLevels = true;
        MapViewport.Eye = new FixedEye();
        TabContainer.SetTabTitle(ListTab, Loc.GetString("rmc-camera-ui-tab-list"));
        TabContainer.SetTabTitle(MapTab, Loc.GetString("rmc-camera-ui-tab-map"));
        TabContainer.SetTabTitle(EditorTab, Loc.GetString("rmc-camera-editor-manage"));
        ManageNetworkButton.Text = Loc.GetString("rmc-camera-editor-manage");
        ManageNetworkButton.OnPressed += _ => MonitorTabs.CurrentTab = EditorTab.GetPositionInParent();

        GridSelector.OnItemSelected += args =>
            CameraMap.SelectGrid((NetEntity) args.Button.GetItemMetadata(args.Id)!);
        CameraMap.CameraSelected += camera => CameraSelected?.Invoke(camera);
        CameraMap.GridChanged += OnCameraMapGridChanged;
    }

    public void UpdateMap(CameraMapUiState state, NetEntity? activeCamera)
    {
        GridSelector.Clear();
        _gridMap.Clear();

        foreach (var grid in state.Grids)
        {
            GridSelector.AddItem(grid.Name);
            var id = GridSelector.ItemCount - 1;
            GridSelector.SetItemMetadata(id, grid.Grid);
            _gridMap[grid.Grid] = id;
        }

        var selectedGrid = CameraMapSelection.SelectGrid(state, _selectedGrid, activeCamera);
        GridSelector.Disabled = selectedGrid == null;
        MapEmptyLabel.Visible = selectedGrid == null;
        CameraMap.Visible = selectedGrid != null;
        CameraMap.SetState(state, activeCamera);

        if (selectedGrid is { } selected && _gridMap.TryGetValue(selected, out var gridId))
            GridSelector.Select(gridId);
    }

    public void SetFeatures(bool mapEnabled, bool editorEnabled)
    {
        MapTab.Visible = mapEnabled;
        EditorTab.Visible = editorEnabled;
        ManageNetworkButton.Visible = editorEnabled;

        var current = MonitorTabs.CurrentTab;
        if ((!mapEnabled && current == MapTab.GetPositionInParent()) ||
            (!editorEnabled && current == EditorTab.GetPositionInParent()))
        {
            MonitorTabs.CurrentTab = ListTab.GetPositionInParent();
        }
    }

    private void OnCameraMapGridChanged(NetEntity? grid)
    {
        _selectedGrid = grid;
        if (grid is { } selected && _gridMap.TryGetValue(selected, out var gridId))
            GridSelector.Select(gridId);
    }
}
