- type: antagJobBlacklist
  id: AllGovforJobs
  jobs:
    - AU14JobGOVFORPlatCo
    - AU14JobGOVFORPlatoonCorpsman
    - AU14JobGOVFORNurse
    - AU14JobGOVFORDCC
    - AU14JobGOVFORPlatOp
    - AU14JobGOVFORDSPilot
    - AU14JobGOVFORRadioTelephoneOperator
    - AU14JobGOVFORRadioTrafficOperator
    - AU14JobGOVFORSquadSergeant
    - AU14JobGOVFORSquadAutomaticRifleman
    - AU14JobGOVFORSquadCombatTech
    - AU14JobGOVFOREngineeringTech
    - AU14JobGOVFORSquadRifleman
    - AU14JobGOVFORAuxSupportSynth
    - AU14JobGOVFORadvisor
    - AU14JobGOVFORMilitaryDoctor
    - AU14JobGOVFORMilitaryPoliceMan
    - AU14JobGOVFORSectionSergeant
    - AU14JobGOVFORAuxTech
    - AU14JobGOVFORWorkingJoe
    - AU14JobGOVFORWeaponsSpecialist
    - AU14JobGOVFORVehicleCrewman
    - AU14JobGOVFORVehicleCommander
    - CMUJobGOVFORDroneOperator

- type: antagJobBlacklist
  id: AllOpforJobs
  jobs:
    - AU14JobOPFORPlatCo
    - AU14JobOPFORPlatoonCorpsman
    - AU14JobOPFORDCC
    - AU14JobOPFORPlatOp
    - AU14JobOPFORDSPilot
    - AU14JobOPFORRadioTelephoneOperator
    - AU14JobOPFORSquadSergeant
    - AU14JobOPFORSquadAutomaticRifleman
    - AU14JobOPFORSquadCombatTech
    - AU14JobOPFORSquadRifleman
    - AU14JobOPFORAuxSupportSynth
    - AU14JobOPFORadvisor
    - AU14JobOPFORMilitaryDoctor
    - AU14JobOPFORMilitaryPoliceMan
    - AU14JobOPFORSectionSergeant
    - AU14JobOPFORAuxTech
    - AU14JobOPFORWorkingJoe
    - AU14JobOPFORVehicleCrewman
#   - CMUJobOPFORDroneOperator
#   - AU14JobOPFORWeaponsSpecialist
